# Generated by Django 3.1.2 on 2020-10-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201028_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='123'),
            preserve_default=False,
        ),
    ]
